packages:
  - "packages/*"

catalog:
  # Pi
  "@earendil-works/pi-agent-core": 0.75.5
  "@earendil-works/pi-ai": 0.75.5
  "@earendil-works/pi-coding-agent": 0.75.5
  typebox: ^1.1.38

  # Effect
  effect: 4.0.0-beta.70
  "@effect/platform-node": 4.0.0-beta.70
  "@effect/sql-sqlite-node": 4.0.0-beta.70
  "@effect/tsgo": ^0.11.0
  "@effect/vitest": 4.0.0-beta.70

  # TypeScript
  typescript: ^6.0.3
  "@typescript/native-preview": 7.0.0-dev.20260525.1
  "@types/node": ^25.9.1

  # Tooling
  oxfmt: ^0.51.0
  oxlint: ^1.66.0
  vitest: ^4.1.7

  # Other deps
  "@modelcontextprotocol/sdk": ^1.29.0
  discord.js: ^14.26.4

allowBuilds:
  '@google/genai': true
  better-sqlite3: true
  cpu-features: true
  koffi: true
  msgpackr-extract: true
  protobufjs: true
  ssh2: true
